### PR TITLE
Support node 0.11 and 0.12 using nan

### PR DESCRIPTION
**Pull request by gierschv**

### CODE REVIEW

**Comment by Jimbly** [comment]
Nice!

**Comment by FGRibreau** [comment]
:+1:

**Comment by Jimbly** [comment]
Seems to still work fine on 0.10, I'll assume you tested 0.12 sufficiently ;).
I've updated the contributors in package.json and published to NPM.

**Comment by gierschv** [comment]
Thanks! Yes, I did :dancers:

**Pull request merged**
